Repository authlib/authlib, pull requests merged in 2025-04, with the labels that each got.

#727 fix(client): add claims_cls parameter for parse_id_token, #725
  .gitignore
  authlib/integrations/base_client/async_openid.py
  authlib/integrations/base_client/sync_openid.py
  authlib/integrations/django_client/apps.py
  authlib/integrations/flask_client/apps.py
  authlib/integrations/starlette_client/apps.py
  docs/changelog.rst
Labels: feature request, server

#728 Fix invalid characters in 'error_description'
  authlib/jose/errors.py
  authlib/oauth2/base.py
  authlib/oauth2/rfc6749/authorization_server.py
  authlib/oauth2/rfc6749/errors.py
  authlib/oauth2/rfc6749/grants/authorization_code.py
  authlib/oauth2/rfc6749/grants/base.py
  authlib/oauth2/rfc6749/grants/client_credentials.py
  authlib/oauth2/rfc6749/grants/implicit.py
  authlib/oauth2/rfc6749/grants/refresh_token.py
  authlib/oauth2/rfc6749/grants/resource_owner_password_credentials.py
  authlib/oauth2/rfc7523/assertion.py
  authlib/oauth2/rfc7523/jwt_bearer.py
  authlib/oauth2/rfc7636/challenge.py
  authlib/oauth2/rfc8628/device_code.py
  authlib/oidc/core/grants/hybrid.py
  authlib/oidc/core/grants/implicit.py
  authlib/oidc/core/grants/util.py
  docs/changelog.rst
  tests/flask/test_oauth2/test_authorization_code_grant.py
Labels: bug, server

#732 Allow `request_object_signing_alg_values_supported` to not contain 'none' and 'RS256'
  authlib/oidc/discovery/models.py
  tests/core/test_oidc/test_discovery.py
Labels: bug, server

#729 Forbid URL fragments in redirect_uris
  authlib/common/urls.py
  authlib/oauth2/rfc7591/claims.py
  docs/changelog.rst
  tests/flask/test_oauth2/test_client_registration_endpoint.py
Labels: bug, server

#733 Fix an issue when rfc9207 is enabled and the authorization response is not a 302
  authlib/oauth2/rfc9207/parameter.py
  docs/changelog.rst
Labels: bug

#739 Update Flask OAuth2 example to show error management
  docs/flask/2/authorization-server.rst
Labels: documentation

#742 Example for RFC7591 generate_client_registration_info
  docs/specs/rfc7591.rst
Labels: documentation

#743 Support for 'acr' and 'amr' claims in id_token
  authlib/integrations/sqla_oauth2/tokens_mixins.py
  authlib/oidc/core/grants/code.py
  authlib/oidc/core/grants/util.py
  authlib/oidc/core/models.py
  docs/changelog.rst
  tests/flask/test_oauth2/models.py
  tests/flask/test_oauth2/test_openid_code_grant.py
Labels: feature request

#751 Fix missing 'state' param in authorization error responses
  authlib/oauth2/rfc6749/authenticate_client.py
  authlib/oauth2/rfc6749/authorization_server.py
  authlib/oauth2/rfc6749/grants/authorization_code.py
  authlib/oauth2/rfc6749/grants/base.py
  authlib/oauth2/rfc6749/grants/implicit.py
  authlib/oidc/core/grants/implicit.py
  docs/changelog.rst
  tests/flask/test_oauth2/test_openid_code_grant.py
Labels: bug, server

#761 Fix `response_types` order unwanted strictness during dynamic client registration
  authlib/oauth2/rfc7591/claims.py
  docs/changelog.rst
  tests/flask/test_oauth2/test_client_registration_endpoint.py
Labels: bug, server

#762 `unsupported_response_type` errors are redirected
  authlib/oauth2/rfc6749/authorization_server.py
  authlib/oauth2/rfc6749/errors.py
  tests/flask/test_oauth2/test_openid_hybrid_grant.py
Labels: bug, server
